export const GET_ERRORS = 'GET_ERRORS';
export const GET_WEATHER_DATA = 'GET_WEATHER_DATA';
export const SET_WEATHER_DATA_LOADING = 'SET_WEATHER_DATA_LOADING';
export const LOAD_WEATHER_DATA = 'LOAD_WEATHER_DATA';
export const RECEIVE_NO_DATA = 'RECEIVE_NO_DATA';
